### ISSUE TITLE
LINQ with Inference new feature

### ISSUE THREAD

**Issue by charbull** [MakoLab/RomanticWeb#68]
I would like to add inference support by query for LINQ while generating SPARQL.

Is there anybody else interested in this feature?

Regards,
Charbel

**Comment by alien-mcl** [comment]
Could you please elaborate a bit more on that feature?

**Comment by charbull** [comment]
When the context factory is connected to a remote persistent storage, it is possible that the store supports inference by query. As described [here](https://github.com/dotnetrdf/dotnetrdf/issues/108).

 In RomanticWeb, we can use LINQ to query the underlying store. If I understood correctly, a LINQ query is translated to a SPARQL query and then sent to the persistent store.

Combining both LINQ and Reasoning activated by query would be really powerful.

Maybe supporting something like this? `context.AsQueryable().WithReasoning()`
The with reasoning parameter will be propagated to the underlying connector of DotNetRDF as in [here](https://github.com/dotnetrdf/dotnetrdf/pull/109).

```C#
IQueryable<IEntity> untypedQuery = from entity in context.AsQueryable().WithReasoning()
                                   where entity is IPerson
                                   select entity;
```
Adding this kind of capabilities will allow developers an advanced capability and avoid writing pure SPARQL outside of RomanticWeb when they would like to activate the reasoning.

It will not be complicated to propose a PR.

Charbel

**Comment by alien-mcl** [comment]
I had a hunch it was about that kind of store's capability. Question is - to what degree this mechanism is transient across various stores. I.e. for Virtuoso I found a SPARQL query should be started with this kind of declaration:
```
DEFINE input:inference 'urn:owl:inference:rules:tests'
```
Clearly it is not a bool. 
Still, I believe this extension could be useful for some scenarios.

**Comment by tpluscode** [comment]
Hm, this would have to be translated differently depending on the store queried. Possibly ignored if unsupported?

**Comment by tpluscode** [comment]
Or, each store that supports reasoning could come with it's own flavor of this extension. Such as

* `RomanticWeb.Virtuoso.QueryExtensions#WithReasoning`
* `RomanticWeb.Stardog.QueryExtensions#WithReasoning`

etc

**Comment by alien-mcl** [comment]
But result of the IEntityContext.AsQueryable<T> is store independent - how would you attach this extension to the queryable instance?

**Comment by tpluscode** [comment]
You tell me. I haven't touched this code in ages ;)

**Comment by charbull** [comment]
This feature of reasoning by query is supported in Stardog and [AllegroGraph RESt API](https://franz.com/agraph/support/documentation/current/http-protocol.html). I am not sure about other stores as I didn't try them out till this step.

I was following this idea:
if the context Factory can be configured to use DotNetRDF and its connectors. Why not pass the reasoning to the underlying Store connector?

I am not sure yet, still digging in the code, a pointer would help :)

**Comment by alien-mcl** [comment]
'EntityContext' and 'EntityContextFactory' are loosely coupled with dotNetRDF - currently it is the implementation of the 'ITripleSource' used, but in theory it can be any other implementation.
Indeed, extension would need to pass that reasoning feature down to that underlying triple source - the question is how this extension's API should look like to be transient across various implementations.

**Comment by alien-mcl** [comment]
@tpluscode - answer to your question - you can't :).
`EntityQueryable` has no clue on what kind of triple source it is using - it's beneath three layers of abstractions :) (`EntityQueryable` has `EntityQueryExecutor` which has instance of the `ITripleSource` which finally knows something about it's underlying triple store)

**Comment by charbull** [comment]
So from `EntityContext` we can call `AsQueryable` to go to `EntityQueryable` then we end up in `EntityQueryExecutor` which knows the store since it has an `EntityStore`,
```C#
 public EntityQueryExecutor(IEntityContext entityContext, IEntitySource entitySource
, IEntityStore store)
        {
            _entityContext = entityContext;
            _entitySource = entitySource;
            _store = store;
            _queryOptimizer = new GenericQueryOptimizer();
        }
```
can we go through the `TripleStoreAdapter` like you handle the commit from the `EntityContext` which goes to `PersistentTripleStoreSparqlCommandExecutionStrategy`

I don't have the full scope of the implementation, just trying to understand.

PS: @alien-mcl I forked your code but couldn't build it. I attached the logs any hints/help?
[logs.txt](https://github.com/MakoLab/RomanticWeb/files/1086479/logs.txt)

Thanks,

**Comment by alien-mcl** [comment]
Way of passing it to the underlying tripple store is not an issue. The issue is how that extension should look like. We can't introduce store-specific extension as the EntityQueryable doesn't have a notion of a store specification. The only thing that I can come with now is:
```csharp
public IQueryable<T> WithReasoning(params EntityId[] reasoningRuleset);
```

This way the extension could be called with explicitly provided iris that Virtuoso could consume and the fact of calling it is enough for stardog.

**Comment by charbull** [comment]
Thx @alien-mcl, I propose a pull request soon.
Any ideas/hints for the builds errors? which version should I work on ? this one, your fork or another

**Comment by alien-mcl** [comment]
Hi @charbull - I could you please provide those build errors again?
As for the question - I'd start with the for. I'll merge it to the main repo some time in future (and rather sooner than later)

**Comment by charbull** [comment]
Hi @alien-mcl, 
I attached the logfiles, not sure if it coming from VS 2017 incompatibility?

Charbel
[RW.txt](https://github.com/MakoLab/RomanticWeb/files/1103058/RW.txt)

[VS.txt](https://github.com/MakoLab/RomanticWeb/files/1103059/VS.txt)
[UpgradeLog.htm.txt](https://github.com/MakoLab/RomanticWeb/files/1103060/UpgradeLog.htm.txt)

**Comment by alien-mcl** [comment]
Indeed final release of VS2017 has .net core projects covered completely different that it was in preview version. From the VS.txt report it looks like the RomanticWeb.Tests projects has no valid reference to the dotNetRDF project. I'll try to make that conversion on my VS - maybe I'll reproduce the issue.

**Comment by charbull** [comment]
@alien-mcl any suggestions? I am still motivated to do this :)

**Comment by charbull** [comment]
Hi @alien-mcl and @tpluscode,
With a colleague, we are trying to move forward on the inference part.

We would appreciate your help in understanding the following:
1- RomanticWeb relies on DotNetRDF to connect for example to Stardog. For example through configuration: 
```
<romanticWeb.dotNetRDF>
  <stores>
    <persistent name="remoteSD">
      <customProvider type="VDS.RDF.Storage.StardogConnector, dotNetRDF">
        <parameters> 
          <add key="baseUri" value="http://localhost:5820/" /> 
          <add key="kbID" value="CharbelDemo" />
        </parameters>
      </customProvider>
    </persistent>
  </stores>
</romanticWeb.dotNetRDF>
```


2- We tried to execute a query from LINQ, we followed the call stack and ended up at 
PersistentTripleStoreSparqlCommandExecutionStrategy( RomanticWeb) which calls PersistentTripleStore (DotNetRDF)

The question is where does StardogConnector comes into the picture? Because we can call the StardogConnector.Query(String sparqlQuery, bool reasoning); since it implements
IReasoningQueryableStorage, IStorageProvider
So we can find a way to set the reasoning from LINQ

Thank you,
Charbel

**Comment by alien-mcl** [comment]
I'm not a dotNetRDF expert, but RomatnicWeb uses `PersistentTripleStore` that is injected with an `IStorageProvider` that StardogConnector seems to implement. I think you should try with CustomProviderElement that should allow you to configure a StardogConnector instance with some parameters injection.

**Comment by charbull** [comment]
Hi @alien-mcl and @tpluscode,

We were able to patch the inference [here](https://github.com/BuildingsLabs/RomanticWeb/blob/develop/RomanticWeb.dotNetRDF/PersistentTripleStoreSparqlCommandExecutionStrategy.cs) but for some reason, we are hitting an timeout exception.

If you have any thoughts on this it would be great,
Thank you

```
VDS.RDF.Query.RdfQueryException : A HTTP error  occurred while querying the Store.
No response, see aforementioned status line or inner exception for further details
  ----> System.Net.WebException : The operation has timed out
   at VDS.RDF.Storage.BaseStardogConnector.Query(IRdfHandler rdfHandler, ISparqlResultsHandler resultsHandler, String sparqlQuery, Boolean reasoning)
   at VDS.RDF.Storage.BaseStardogConnector.Query(String sparqlQuery, Boolean reasoning)
   at RomanticWeb.DotNetRDF.PersistentTripleStoreSparqlCommandExecutionStrategy.ExecuteSelect(IQuery sparqlQuery, SparqlQueryVariables& variables) in C:\Users\SESA180908\Documents\GitHub\RomanticWeb\RomanticWeb.dotNetRDF\PersistentTripleStoreSparqlCommandExecutionStrategy.cs:line 91
   at RomanticWeb.DotNetRDF.TripleStoreAdapter.ExecuteScalarQuery(IQuery queryModel) in C:\Users\SESA180908\Documents\GitHub\RomanticWeb\RomanticWeb.dotNetRDF\TripleStoreAdapter.cs:line 123
   at RomanticWeb.Linq.EntityQueryExecutor.ExecuteScalar[T](QueryModel queryModel)
   at Remotion.Linq.Clauses.StreamedData.StreamedScalarValueInfo.ExecuteScalarQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.Clauses.StreamedData.StreamedScalarValueInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at Wpa.Rdf.RomanticWeb.ContextFactoryHelper.ValidateContextFactory(String providerName, EntityContextFactory entityContextFactory)
   at Wpa.Rdf.RomanticWeb.ContextFactoryHelper.CreateFactoryAndAddToCache(String providerName, String nameSpace)
   at Wpa.Rdf.RomanticWeb.ContextFactoryHelper.CreateContext(String providerName, String nameSpace)
   at Wpa.Rdf.RomanticWeb.RdfContext..ctor(String providerName, String nameSpace)
   at Wpa.Rdf.Test.TestHelpers.CreateTestContext(String providerName)
   at Wpa.Rdf.Test.TestHelpers.CreateDataLoader(String providerName)
   at Wpa.Rdf.Test.WpaFixture.Can_create_city(String cityName, String stateName, String countryName)
--WebException
   at System.Net.HttpWebRequest.GetResponse()
   at VDS.RDF.Storage.BaseStardogConnector.Query(IRdfHandler rdfHandler, ISparqlResultsHandler resultsHandler, String sparqlQuery, Boolean reasoning)
```

**Comment by alien-mcl** [comment]
Hmm - seems Stardog did not respond timely fasion. Did you try to peek the URL that is send to the server? Any HTTP sniffer should give you a hint. Once obtained, you could just call it from any client to check whether it times out as well.
